@startuml
actor  T1
actor  T2
actor  T3
T1 --> T1 : 开启事务1
T2 --> T2 : 开启事务2
T1 --> T1 : 额外业务处理逻辑
T1 --> T1 : 获取商户账变锁
T1 --> T1 : 商户账变
T3 --> T3 : 开启事务3
T2 --> T2 : 额外业务处理逻辑
T1 --> T1 : 事务提交
T2 --> T2 : 获取商户账变锁
T3 --> T3 : 额外业务处理逻辑
T2 --> T2 : 商户账变
T2 --> T2 : 事务提交
T3 --> T3 : 获取商户账变锁
T3 --> T3 : 事务提交
@enduml

