@startuml

package "其他商户账变业务流程" {
  [订单确认]
  [订单取消]
}

package "其他渠道相关业务流程" {
  [渠道下单]
}

cloud {
  [外部商户提款下单前置逻辑]
}
cloud {
  [外部商户提款下单后置逻辑]
}
database "数据库事务" {
  folder "计算商户账户账变" {
    [商户账变锁]
  }
  folder "支付渠道" {
    [渠道支付锁]
  }
}
下单请求 - [外部商户提款下单前置逻辑]
[外部商户提款下单前置逻辑] --> [商户账变锁]
[商户账变锁] --> [渠道支付锁]
[渠道支付锁] --> [外部商户提款下单后置逻辑]
[外部商户提款下单后置逻辑] - 处理完成

[订单确认] --> [商户账变锁]
[订单取消] --> [商户账变锁]
[渠道下单] --> [渠道支付锁]
@enduml
